# -*- coding: utf-8 -*-

from . import controllers
from . import bill_controllers
from . import server_controllers
from . import bidding_channel_controller
from . import bidding_notification_user_rel_controller
from . import bidding_order_controller
from . import bidding_driver_controller
from . import bidding_order_receive_controller
from . import bidding_order_return_controller
from . import bidding_package_controller
from . import bidding_vehicle_controller
from . import bill_lading_detail_controller
from . import cargo_controller
from . import cargo_price_controller
from . import company_award_controller
from . import distance_compute_controller
from . import distance_unit_controller
from . import sharevan_bill_package_routing_plan_controller
from . import product_type_controller
from . import routing_plan_day_controller
from . import sharevan_hub_controller
from . import sharevan_notification_controller
from . import sharevan_routing_plan_day_service_controller
from . import sharevan_service_type_controller
from . import sharevan_warehouse_controller
from . import sharevan_subscribe_controller
from . import sharevan_employee_warehouse_controller
from . import stock_man_controller
from . import res_partner_controller
