# -*- coding: utf-8 -*-

from . import bidding_channel
from . import bidding_driver
from . import bidding_notification
from . import bidding_notification_user_rel
from . import bidding_order
from . import bidding_order_receive
from . import bidding_order_return
from . import bidding_package
from . import bidding_vehicle
from . import bill_lading_detail
from . import bill_package_routing
from . import cargo
from . import cargo_price
from . import company_award
from . import distance_compute
from . import fleet_driver
from . import fleet_vehicle
from . import measure_unit
from . import models
from . import product_type
from . import res_country
from . import res_partner
from . import res_user
from . import service_distance_fee
from . import service_weight_fee
from . import sharevan_area
from . import sharevan_bidding_award_rel
from . import sharevan_bill_lading
from . import sharevan_bill_package_routing_export
from . import sharevan_bill_package_routing_import
from . import sharevan_employee_warehouse
from . import sharevan_hub
from . import sharevan_insurance
from . import sharevan_notification
from . import sharevan_notification_user_rel
from . import sharevan_price_quotation
from . import sharevan_province
from . import sharevan_recurrent
from . import sharevan_routing_plan_day_service
from . import sharevan_warning_type
from . import sharevan_zone
from . import sharevan_zone_price
from . import size_standard
from . import subcribe
from . import warehouse
